services:
  api-service:
    build: ./Backend
    env_file:
      - ./Backend/.env
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
    volumes:
      - ./Backend/app:/app/app

  celery-worker:
    build: ./Backend
    command: celery -A app.celery_worker worker --loglevel=WARNING --concurrency=5
    container_name: celery-worker
    networks:
      - backend
    env_file:
      - ./Backend/.env

  redis:
    container_name: redis-db
    image: redis:8-alpine
    networks:
      - backend
    volumes:
      - redis-data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
  frontend:
